public/css/gentella/custom.min.css

se corrigio un valor del logo principal no se mostraba correctamente

SE CORRIGIO UN ERROR EN EL ESTILO DEL LOGO

---

controller/cliente.php
model/clienteDAO.php
model/clienteDTO.php
view/cliente/cliente.php

Modulo completo de los clientes
-Registra y actualiza imagenes

MODULO COMPLETO DE CLIENTES

---

controller/aboutUs.php
controller/cliente.php
controller/dashboard.php
controller/gimnasio.php
controller/permisosRol.php
controller/planGym.php
controller/planSistema.php
controller/rol.php
controller/usuario.php
logout.php
view/aboutUs/index.php
view/cliente/cliente.php
view/dashboard/aboutUs.php
view/dashboard/index.php
view/gimnasio/index.php
view/menu.php
view/planGym/index.php
view/planSistema/index.php
view/rol/rol.php
view/usuario/index.php

Se borraron los session_start de los controladores y se pasaron a las vistas.

Se cambio el session_start del controlador a las vistas

---

controller/pago.php
controller/planGym.php
model/clienteDAO.php
model/pagoDAO.php
model/pagoDTO.php
model/planGymDAO.php
model/planGymDTO.php
model/usuarioDAO.php
model/usuarioDTO.php
view/menu.php
view/pago/index.php

Se agrego modulo de pago completo, y se realizaron dos consultas para traer los clientes y los  planes de gimnasio.

Se agregó modulo de pago completo

---

controller/cliente.php
controller/planGym.php
controller/planSistema.php
controller/rol.php
controller/usuario.php
model/clienteDAO.php
model/clienteDTO.php
model/planGymDAO.php
model/planSistemaDAO.php
model/rolDAO.php
model/usuarioDAO.php
model/usuarioDTO.php
view/cliente/cliente.php
view/menu.php
view/planGym/index.php
view/planSistema/index.php
view/rol/rol.php
view/usuario/index.php

En modulo Cliente se arreglo el insert, se agregaron dos campos  id_gimnasio y id_planGym, se arreglo el modal para que muestre los detalles, Se arreglo el modulo Plan Gym, agregandole un nuevo campo id_gimnasio,se arreglo la consulta que trae los datos, En el modulo Usuario se arreglo el insert y update y la consulta SQL para traer datos.

Se creo Un modal para asignar gimnasio y plan sistema.

---

controller/cliente.php
controller/permisosRol.php
controller/usuario.php
model/usuarioDAO.php
view/cliente/cliente.php
view/menu.php
view/usuario/index.php

la genereación de credencial para que se descargue,
el nombre de la funcion para asignar.

Se corrigierón las URL

---

controller/cliente.php
model/clienteDAO.php
view/cliente/cliente.php

Se agrego el campo de email en los formularios de clientes, para que el usuario pueda almacenar el email de los clientes en la base de datos. 
Se agrego en en el formulario de registro, actualización de registro y se muestra el email en el data table de clientes

FFIT-21 Se agrego el campo de email en los formularios de clientes

---

model/usuarioDAO.php
view/main/index.php

FFIT-37 Se debe de mostrar una advertencia de que su pago ya vencio en el login, solo para los gerentes que estan inactivos, porque su pago ya esta vencido

FFIT-37-modulo-advertencia-pago-vencido-en-el-login-de-los-gerentes

---

controller/cliente.php
controller/services/validarPermisoModulo.php
view/cliente/cliente.php

Este PR es solo una prueba para ver si funciona correctamente la validación de urls en el servidor

FFIT-22 Validacion de Urls

---

controller/cliente.php
controller/dashboard.php
controller/gimnasio.php
controller/pago.php
controller/planGym.php
controller/planSistema.php
controller/rol.php
controller/services/validatePermissionModule.php
controller/services/validateSession.php
controller/usuario.php
controller/visitaCliente.php
model/usuarioDAO.php
view/cliente/cliente.php
view/dashboard/index.php
view/gimnasio/index.php
view/pago/index.php
view/planGym/index.php
view/planSistema/index.php
view/rol/rol.php
view/usuario/index.php
view/visitaCliente/index.php

En este PR se valida que el usuario tenga permisos para acceder a las vistas, en donde si tiene permiso, le permite el acceso, y si no, lo redirige a la pagina de error 404
También, se le niega el permiso de acceder a los usuarios que no han pagado por usar el sistema, ajustando la posición de los session

FFIT-22 validar permisos de urls en todas las vistas

---

controller/cliente.php
model/clienteDAO.php
model/clienteDTO.php
model/pagoDAO.php
model/pagoSistemaDAO.php
model/usuarioDAO.php
model/usuarioDTO.php
view/cliente/cliente.php
view/pago/index.php
view/pagoSistema/index.php
view/usuario/index.php

FFIT-27 Se debe de mostrar correctamente el capo de plan gimnsio en el formuario de actualizar el pago del gerente, como tambien corregir todos los campos que no se muestran en los formuarios de actualizar

FFIT-27-modulo-bug-campos-en-los-formuarios-actualizar

---

controller/cliente.php
controller/gimnasio.php
controller/pago.php
controller/pagoSistema.php
controller/planGym.php
controller/planSistema.php
controller/rol.php
controller/usuario.php
controller/visitaCliente.php
model/clienteDAO.php
model/gimnasioDAO.php
model/pagoDAO.php
model/pagoSistemaDAO.php
model/planGymDAO.php
model/planSistemaDAO.php
model/rolDAO.php
model/usuarioDAO.php
model/visitaClienteDAO.php

FFIT-33 No se debe de mostrar la notificacion del datatable cuando no hay registros en la tablas, de todos los modulos existentes en del sistema

FFIT-33-eliminar-notificacion-del-data-table-cuando-no-hay-registros

---

libs/conexion.php
model/usuarioDAO.php

FFIT-23 Se debe de dar seguridad al login, para que no puedan entrar por inyecccion sql, esto se hizo por consultas preparadas.

FFIT-23-inyeccion-de-sql-en-el-login

---

controller/cliente.php
controller/dashboard.php
controller/emails/sendExpiredNotificationCustomer.php
controller/pagoSistema.php
controller/usuario.php
model/clienteDAO.php
model/dashboardDAO.php
model/pagoSistemaDAO.php
model/pagoSistemaDTO.php
model/usuarioDAO.php
model/usuarioDTO.php
view/cliente/credencial/plantilla.php
view/dashboard/index.php
view/pagoSistema/index.php
view/usuario/index.php
view/visitaCliente/index.php

Se modifico el código para que tanto el gerente como el administrador, puedan observar las graficas de ganancias, como también los clientes o usuarios del lado del administrador, que están por vencer sus membrecías, todo ello desde la misma vista del dashboard.
Para ello se crearon agregaron nuevos campos en la base de datos como la cantidad del pago en la tabla de pago_plan_sistema y en la tabla de usuario se agregaron dos campos, telefonoUsuario y isEmailNotified
*script*
ALTER TABLE pago_plan_sistema
ADD cantidad_pago INT;
ALTER TABLE usuario
ADD telefonoUsuario VARCHAR(10),
ADD isEmailNotified BOOLEAN DEFAULT 0;
algunos de los bugs corregidos son 
*ruta de la imagen de la credencial de los clientes del gerente
*actualización de clientes(error de merge)
*error de urls en visitaCliente …

FFIT-32 Graficas en el rol de administrador y algunos bugs

---

controller/usuario.php
model/clienteDAO.php
model/dashboardDAO.php
model/pagoDAO.php
model/pagoSistemaDAO.php
model/usuarioDAO.php
view/perfil/index.php
view/usuario/index.php

se agrego un botón para editar la contraseña de los usuario en el rol del admin, quitando la del formulario de actualizar datos, y guardando la contraseña encriptada con sha1, para ello se ajusto el campo de contraseña en la tabla de usuario para poder almacenar 40 caracteres.
También se ajusto la consulta de la tabla de clientes y usuario con membresías por vencer para que cuando se haga el pago, ya no aparezca en la tabla de membresías por vencer
Actualizar el campo de isEmailNotified para cuando se hace un pago

FFIT-38 boton para cambiar contraseña de los usuarios en el rol admin

---

config/db/migrations/20231006153829_crear_tabla_pago_plan_sistema.php
config/db/migrations/20231010153331_visita_cliente.php
config/db/seeds/Cliente.php
config/db/seeds/Gimnasio.php
config/db/seeds/Modulo.php
config/db/seeds/PagoSistema.php
config/db/seeds/Permiso.php
config/db/seeds/PlanSistema.php
config/db/seeds/Usuario.php
config/db/seeds/UsuarioGimnasio.php
config/db/seeds/VisitaCliente.php

FFIT-40 Se agregero y corregio campos faltantes a tablas de la migraciones, como tambien se agregaron dos seeders nuevos y campos para el demo.

FFIT-40-modulo-migraciones-y-seeders-para-el-demo

---

controller/emails/sendExpiredNotificationCustomer.php
view/cliente/cliente.php
view/cliente/credencial/plantilla.php
view/dashboard/index.php
view/gimnasio/index.php
view/perfil/index.php
view/usuario/index.php
view/visitaCliente/index.php

En este PR se corrige la visualización de imágenes, en donde la imagen no esta registrada en la base de datos o no esta almacenada en el sistema. los cambios son en:
modulo visita cliente
tabla de visita cliente
Modulo cliente
tabla de clientes
modal para visualizar la imagen antes de actualizarla
credenciales de clientes
Modulo de usuario
tabla de usuarios
modal para visualizar la imagen antes de actualizarla
Modulo gimnasio
tabla de gimnasios
modal para visualizar la imagen antes de actualizarla
Modulo dashboard
tabla de clientes y usuarios
Modulo Perfil
foto de perfil del usuario

FFIT-41 Correccion de visualizacion de imagenes

---

model/pagoDAO.php
public/css/about/about.css
public/css/about/styles.css
view/aboutUs/index.php
view/pago/index.php

FFIT-43 Se pondra el nombre copleto de los clientes en el select del pago, como tambieen se mejorar la parte de acerca de nostros del sistema

FFIT-43-nombre-completo-en-pago-y-acerca-de-nostros

---

config/db/migrations/20231205051751_add_column_fondo_credencial_tabla_gimnasio.php
controller/cliente.php
controller/gimnasio.php
model/clienteDAO.php
model/gimnasioDAO.php
model/gimnasioDTO.php
view/gimnasio/index.php

En este PR los gerentes le envían su propio fondo de las credenciales de los clientes, para que cada gimnasio tenga su propio diseño de la credencial de sus clientes

FFIT-45 fondos de credenciales registrados por el administrador

---

.env.example
README.md
composer.json
config/config.php

1Se corrigio el config.php, README, .env.example, y el archivo composer.json

FFIT-47 Se corrigierón errores

---

controller/pagoSistema.php
model/pagoSistemaDAO.php
model/pagoSistemaDTO.php
view/pagoSistema/index.php

1. Llenar los campos cantidad y plan sistema por default una vez que se selecciona un usuario

FFIT-52 Llenar los campos cantidad y plan sistema del formulario pago sistema

---

controller/pago.php
model/pagoDAO.php
view/pago/index.php

cuando se selecciona el cliente los datos se llenan en automatico en el apartado de registrar pago

FFIT-51 cantidad y nombre en el apartado registrar pago automatico

---

controller/dashboard.php
model/gimnasioDAO.php
view/dashboard/index.php
view/dashboard/plantillaReporteIngresos.php

se agrego un boton en el ashborad y genera el reporte

FFIT-54 Generacion de reporte de ganancias

---

model/gimnasioDAO.php
view/dashboard/index.php
view/dashboard/plantillaReporteIngresos.php

FFIT-70 <Correcciones del botón que genera el reporte de ingresos par que solo se muestre al gerente del gimnasio y personalización del reporte en el logo dependiendo el gimnasio y se quitan las filas duplicadas>

FFIT-70-error-al-generar-el-pdf-de-ganacias
